### ISSUE TITLE
Uploading stl/cws

### ISSUE THREAD

**Issue by kloknibor** [area515/Creation-Workshop-Host#106]
Hi,

When I try to upload an .cws file than at first I get by default only image formats. Would it be possible to just show all possible files? (So .cws | .stl | All image extensions that are supported | .txt) Etc etc ?

Thanks

**Comment by WesGilster** [comment]
The browser's filetype dropdown list now shows all of the filetypes for all PrintFileProcessors that are enabled in your config.properties file. It also shows .html files(in IE), which is kindof annoying.

**Comment by jmkao** [comment]
Cool, this appears to work. I'm seeing all the registered file extensions from the processors, including cws, stl, zip, and imgzip show up now.
