### ISSUE TITLE
remote install not working

### ISSUE THREAD

**Issue by kloknibor** [area515/Creation-Workshop-Host#123]
Hi,

I can't get the remote isntall to work. It gives an error after reboot and doesn't get started... A youtube clip of it can be found here: https://www.youtube.com/watch?v=m-zmTvY1v9Y

hope it is enough to show you the problem :)

**Comment by WesGilster** [comment]
Great, the video tells me everything. I've noticed that my Raspberry Pi reboots in about 27 seconds, and CWHClient will timeout looking for it after 30.  It seems maybe I'm pushing the limit on this timeout because your's wasn't found after 30 seconds... I'll increase this further and release a version for you tonight.

**Comment by WesGilster** [comment]
I doubled the time allowed to find the Raspberry Pi. This should work fine in cwh-0.219.

**Comment by kloknibor** [comment]
Nearly perfect! : http://youtu.be/MZs1sxORWR8 the not found install pop up comes up again with an not yet compatible mote, when I close it He finds my printer and it works like a charm!

**Comment by WesGilster** [comment]
I fixed the current issue in cwhClient-0.220. Although I've left one issue unsolved, where it will continue to run forever if cwhClient is never found. I'll fix this tomorrow. 

Ultimately, all of these issues stem from the fact that cwhClient is a mess. Lot's of ideas were just kindof thrown together. Once we start have a small set of community maintained printer profiles setup, we'll need to tackle the cwhClient rewrite. It's actually a pretty small task, but not worth taking until we have all the functionality we think we'll want in it...

**Comment by WesGilster** [comment]
All issues fixed in cwhClient-0.222. Let me know if everything looks good and I'll push to prod.

**Comment by kloknibor** [comment]
1 year	2 year	3 year	price Period¹
.com	 € 8,99	€ 9,99	€ 8,99	1 jaar

**Comment by WesGilster** [comment]
This should be retested now that you can choose to install a printer on CWH installation.

**Comment by kloknibor** [comment]
Worked like a charm last time I used it :)!

**Comment by kloknibor** [comment]
Sorry doesn't work like a charm anymore... Just tested latest version... browseprinter seems te be broken in the client version ;)! I only get -cp and the area515.resinprinter.somemore and than it closes immediately...!

**Comment by WesGilster** [comment]
There were some dependency problems that needed to be resolved. Should be fixed now in cwh0.254.

**Comment by kloknibor** [comment]
worked for me like a charm can be closed
