### ISSUE TITLE
Expand root partition on first boot

### ISSUE THREAD

**Issue by kloknibor** [area515/Creation-Workshop-Host#153]
Hi,

I think expanding the root partition on first (re)boot after CWH is installed would be a nice function. This way you don't have to touch any SSH terminal at all :)! Just install CWH and it will make sure it gets out of the pi what is in it!

Robin

**Comment by WesGilster** [comment]
This is already happening on install, plus the camera is also being enabled on install.

**Comment by kloknibor** [comment]
Great! Can be closed than!
