### ISSUE TITLE
Development version breaks performance of CWH due to bulb hours calculation

### ISSUE THREAD

**Issue by WesGilster** [area515/Creation-Workshop-Host#163]
I'm testing the latest dev version of CWH and Bulb hours calculation it happening on every slice. This causes huge performance hit. I'll fix as a part of my "User friendly" release

**Comment by kloknibor** [comment]
Could this function be disabled in settings? Since I use and LCD printer :)

**Comment by WesGilster** [comment]
If your LCD screen supports bulb hours querying(which I doubt that it does) then you would want to know the intensity of the brightness as it decreases with age.

If none of that is supported(which it isn't) it's just not supported... Not sure what your question I fully understand the question.

**Comment by WesGilster** [comment]
I'm testing this in version: cwh-0.259.zip
