### ISSUE TITLE
Disable gradient bulb center

### ISSUE THREAD

**Issue by kloknibor** [area515/Creation-Workshop-Host#165]
Hi,

I'm trying to disable the gradient transparancy thing... It's unneeded for LCD and makes my print fails... I use CWS files but can't get this off... Tried to set the transparancy to 0.0 instead of 0.2 under gradient but didn't work.

Robin

**Comment by kloknibor** [comment]
![image1](https://cloud.githubusercontent.com/assets/10560390/13555046/26e141d4-e3b7-11e5-86c1-4b3ad0ed195d.JPG)

this is how it looks...

**Comment by kloknibor** [comment]
I guess I need to change something here : 

var bulbCenter = new Packages.java.awt.geom.Point2D.Double($buildPlatformXPixels / 2, $buildPlatformYPixels / 2);
var bulbFocus = new Packages.java.awt.geom.Point2D.Double($buildPlatformXPixels / 2, $buildPlatformYPixels / 2);
var totalSizeOfGradient = $buildPlatformXPixels > $buildPlatformYPixels?$buildPlatformXPixels:$buildPlatformYPixels;
var fractions = [0.0, 1.0];
//Let's start with 20% opaque in the center of the projector bulb
var colors = [new Packages.java.awt.Color(0.0, 0.0, 0.0, 0.2), new Packages.java.awt.Color(0.0, 0.0, 0.0, 0.0)];
new Packages.java.awt.RadialGradientPaint(
	bulbCenter,
	totalSizeOfGradient,
	bulbFocus,
	fractions,
	colors,
	java.awt.MultipleGradientPaint.CycleMethod.NO_CYCLE)

I already tried to change the 0.2 to 0.0 doesn't work for me so far :(

**Comment by kloknibor** [comment]
fixed it... Had to press save when printer is disabled... Sorry for bothering!

**Comment by WesGilster** [comment]
No problem. I believe I've tested this with no formula at all. That's most likely what you want. If that doesn't work it's a bug.
