### ISSUE TITLE
Ability to upload fonts

### ISSUE THREAD

**Issue by WesGilster** [area515/Creation-Workshop-Host#173]

**Comment by WesGilster** [comment]
Available in version cwh-0.259.zip

**Comment by kloknibor** [comment]
what file format should it be? ttf? otf? zip?

**Comment by WesGilster** [comment]
ttf

**Comment by WesGilster** [comment]
The font registers quite nicely with the JVM, and is shown in the font list after refreshing the page. Haven't tested a print yet, but I can't see why it wouldn't work.
