### ISSUE TITLE
Branding Changes: CWH --> Photonic3D

### ISSUE THREAD

**Issue by jmkao** [area515/Creation-Workshop-Host#177]
Need to update:
 - Name of repo
 - Names of forks
 - Text in README.md
 - Text in HTML
 - Name of zips

anything else?

**Comment by kloknibor** [comment]
Maybe also the instal folder (easy to adjust) but maybe even the filenames with cwh in it? Like cwh.log but I suppose there are more ;)!

**Comment by WesGilster** [comment]
Exciting... What about all of the code?

**Comment by WesGilster** [comment]
and the entire directory structure where CWH is stored.

**Comment by jmkao** [comment]
At this stage, I think we probably do not need to go below UI and public site-facing strings, so code or log file name changes are probably not necessary. Although Eclipse can probably do many of those renaming changes fairly easily.

**Comment by WesGilster** [comment]
Makes sense to me, it all depends on how far you want to cut...

**Comment by jmkao** [comment]
Github automatically creates redirects from the old repo name, so here's one potential plan:

1. Update HTML and README in WesGilster/CWH
1. Push to area515/CWH
1. Rename area515/CWH to area515/Photonic3D
1. We each update our forks and then start updating the build scripts (which will still work with the old names too, because of the automatic redirects, so step 3 will not break anything)
1. We do a second pass update with the build files and URLs updated

**Comment by WesGilster** [comment]
Yep, I was thinking something similar. No migration needed, and you keep backwards compatibility.

**Comment by jmkao** [comment]
To reduce the amount of work, renaming the zips may not even be necessary. Split this into 3 phases: #203, #204, #205
