### ISSUE TITLE
Change in photocentric profile

### ISSUE THREAD

**Issue by kloknibor** [area515/Creation-Workshop-Host#181]
Hi,

I see I left an fault in the Photocentric config... I have used the following for comport of projector: 

"PortName":"Select a Serial Port...",

I think this must be just null right? Can you change this in area515 also @WesGilster ? Thanks!

**Comment by WesGilster** [comment]
I fixed this, but you can go right into area515 repo on github and browse to the file and change it direct on github. That's all I did...

**Comment by kloknibor** [comment]
I haven't got acces... Only to fork it ;)
