### ISSUE TITLE
Slicing Calculators Don't Recompute Unless Server Is Restarted

### ISSUE THREAD

**Issue by jmkao** [area515/Creation-Workshop-Host#187]
In the latest WesGilster/CWH dev build, at least for the "Test" button (haven't yet tried printing), changes to the slicing calculators do not update the graphs displayed until I restart the server. This may be due to some of the changes relating to compilation of JavaScript and I just might have caught an intermediate state of the feature in-progress.

**Comment by WesGilster** [comment]
Ah. Nice catch. This happened when I started compiling the JavaScript and caching the compiled version into the printer. Currently the "printer" is a stubbed printer for testing purposes. I'll have to flush the cache on all manual printer tests.

**Comment by WesGilster** [comment]
This was fixed long ago. Reopen if you find differently.
