### ISSUE TITLE
No zips dev repo

### ISSUE THREAD

**Issue by kloknibor** [area515/Creation-Workshop-Host#195]
Since the build script doesn't create .zip files in the dev repo of wesgilster anymore it is hard to help testing it :P Might it be possible to auto create these again?

Thanks

**Comment by jmkao** [comment]
Use newstart.sh instead of start.sh in the dev repo.

**Comment by kloknibor** [comment]
Alright will give it a go thanks :)!

**Comment by kloknibor** [comment]
works like a charm... well the start script...
