### ISSUE TITLE
dev repo wes error at start print

### ISSUE THREAD

**Issue by kloknibor** [area515/Creation-Workshop-Host#196]
Hi,

I'm having an error when I try to start a printer with everything simulated. I got a fresh copy of raspbian jessie light, ran newstart.sh (after wget and chmod) installed photocentric printer. Changed all ports to simulated except projector left that choose serial port. And got an long http 500 popup with in reason a jetty erro, logs here : 

[LogBundle.zip.pdf](https://github.com/area515/Creation-Workshop-Host/files/198561/LogBundle.zip.pdf)

**Comment by jmkao** [comment]
It looks like the X server didn't start properly on your box. Do you have the screen output from running newstart.sh that shows what happened when the start script was run?

**Comment by kloknibor** [comment]
no I forgot to copy it :( will try to reproduce later

**Comment by WesGilster** [comment]
Is this possible to reproduce?

**Comment by kloknibor** [comment]
Gonna try it tonigh

**Comment by kloknibor** [comment]
Sorry tomorrow I mean
