### ISSUE TITLE
Windows dev not working

### ISSUE THREAD

**Issue by kloknibor** [area515/Creation-Workshop-Host#197]
Hi,

I downloaded the latest CWH version from releases at the wesgilster repo. I unzipped it and ran the start.bat When I choose to install one of the 2 template printers I get the following error : 

Unrecognized field "Font" (class org.area515.resinprinter.printer.SlicingProfile), not marked as ignorable (41 known properties: "LiftDistance", "DotsPermmX", "TestExposureStep", "DotsPermmY", "PlatformTemp", "TwoDimensionalSettings", "UseMainLiftGCode", "name", "MinTestExposure", "XOffset", "YOffset", "ProjectorGradientCalculator" [truncated]]) at [Source: HttpInputOverHTTP@3fcfa433; line: 1, column: 3180] (through reference chain: org.area515.resinprinter.printer.Printer["configuration"]->org.area515.resinprinter.printer.PrinterConfiguration["slicingProfile"]->org.area515.resinprinter.printer.SlicingProfile["Font"])

error log here : https://www.dropbox.com/s/g5soy1hbs61jhq1/LogBundle%20%281%29.zip?dl=0

Ps sweet to add the download button :)!

**Comment by WesGilster** [comment]
Darn, I was afraid of that one. I thought I tested that. I moved Font and FontSize to a different location in the JSON file(under 2d file properties) and it's not expected in the same place as what you have checked into the Repo. Removing them out of your printer configuration is the best route...

**Comment by kloknibor** [comment]
This also happens with the MuVe from your repo :$ So that should be changed too :)

**Comment by WesGilster** [comment]
This should be fixed in the latest dev version.

**Comment by kloknibor** [comment]
Works now!
