### ISSUE TITLE
Donation by 3Dfacture for the hard work :)

### ISSUE THREAD

**Issue by kloknibor** [area515/Creation-Workshop-Host#20]
So I'm in contact with 3DFacture while they funded their new printer, they wanna thank you for the hard work and I can lower my pledge if I buy a camera and a raspberry pi 2 for you as a thanks to you guys ;)! Shall I just donate money somewhere or can I Send the components to one of you guys?

**Comment by WesGilster** [comment]
That sounds great. I'm working on a websocket solution to eliminate the refresh buttons now, so I won't get to this right away. Do you know my email address already? If so, send me a quick message outside of github and we'll exchange shipping info privately there. I'll just have you order it and specify me as the shipping address.

**Comment by kloknibor** [comment]
I don't have your email adress yet, contact me on robinkolk@msn.com so we can arrange it :)!

**Comment by kloknibor** [comment]
Send you an email :)

**Comment by WesGilster** [comment]
I've sent you a response.

**Comment by WesGilster** [comment]
I believe we've settled this now.
