### ISSUE TITLE
/printers/executeGCode only returns only "ok" w/o command response

### ISSUE THREAD

**Issue by jmkao** [area515/Creation-Workshop-Host#214]
The executeGCode REST API call seems to return only the last line from the printer firmware, which omits any data response for M commands.

For instance, when executing an M114 (to get the current print position), the API returns only "ok". The data part of the response is only visible in `cwh.log`. This makes it hard to implement functionality that might require information from the printer (like a current position display, or something to show and allow you to change the acceleration):

![image](https://cloud.githubusercontent.com/assets/2078819/14758972/96948c32-08c6-11e6-889e-298181cceef9.png)

```
2016-04-23 03:10:40,360 INFO o.a.r.g.GCodeControl [qtp31345842-12] Write: M114

2016-04-23 03:10:40,663 INFO o.a.r.g.GCodeControl [qtp31345842-12] lineRead: X:0.000 Y:3.000 Z:196.000 E:0.000 Count X: 0.000 Y:2.997 Z:196.000

2016-04-23 03:10:40,666 INFO o.a.r.g.GCodeControl [qtp31345842-12] lineRead: ok
```

**Comment by WesGilster** [comment]
If you want to test this, and see if it works to your liking, I'll promote our build to production.

**Comment by WesGilster** [comment]
Wait first, we need to delete start.sh and newstart.sh to start.sh correct?

**Comment by jmkao** [comment]
You can still check in the cwh-0.XXX.zip as before, but I think that newstart.sh seems ready to go.

The only difference for prod is do not use the `fullRelease` gradle target. Just push a tag and CI will take care of the release.

**Comment by jmkao** [comment]
Cool, it works well. Looks GTG.

![image](https://cloud.githubusercontent.com/assets/2078819/14849702/c539468e-0c74-11e6-914b-0c7d279b790a.png)
