### ISSUE TITLE
Printer configurations are being pushed through xml conversion

### ISSUE THREAD

**Issue by WesGilster** [area515/Creation-Workshop-Host#224]
Be careful how you build your printer profiles. You aren't going to want to allow your browser to perform any xml escaping on any of your values. For example I found that both the photocentric and Titan printer profiles that are checked into github have lt; and gt; escapes in them. I'm pretty sure this is going to muck up your gcode templates.

After testing the photocentric profile, this is what it will send to the printer...
G1{$SlideTiltVal != 0? X$SlideTiltVal:} Z(0 * 1) F{0 &lt; 4?$ZBottomLiftRate:0}; G1{$SlideTiltVal != 0? X($SlideTiltVal * -1):} Z((0.1-0) * 1) F$ZRetractRate;&lt;Delay&gt; %d(0*60000/$ZRetractRate+200)

Not good.

**Comment by jmkao** [comment]
I see what happened. I copied them out of the XML file, and those are saved with entity escaping to make it legal XML. They need to be copied out of the UI in order for the entities to be unescaped, or else hand fixed. Fixing them now.
