### ISSUE TITLE
Can't build anymore

### ISSUE THREAD

**Issue by kloknibor** [area515/Creation-Workshop-Host#247]
Hi,

I'm having trouble building after the latest pulls from Wesgilster and even area515. I haven't changed a thing in my set-up only ran windows update and installed a game and the commands java and javac both run fine.

Does it still run fine with you guys? If so it will be something on my local machine. But I'm unsure what it would be since javac an java run fine, java sdk is installed. The command` gradlew` runs fine. But `gradlew run `and `gradlew fullRelease` fail

This is the debug log : 

11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.dependencies using tasks.addPlaceholderAction(dependen
cies)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.dependencies' to state Discovered.

11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.dependencyInsight' rule action tasks.add
PlaceholderAction(dependencyInsight)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.dependencyInsight using tasks.addPlaceholderAction(dep
endencyInsight)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.dependencyInsight' to state Discov
ered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.distTar' rule action Project.<init>.task
s.distTar()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.distTar using Project.<init>.tasks.distTar()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.distTar' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.distZip' rule action Project.<init>.task
s.distZip()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.distZip using Project.<init>.tasks.distZip()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.distZip' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.eclipse' rule action Project.<init>.task
s.eclipse()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.eclipse using Project.<init>.tasks.eclipse()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.eclipse' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.eclipseClasspath' rule action Project.<i
nit>.tasks.eclipseClasspath()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.eclipseClasspath using Project.<init>.tasks.eclipseCla
sspath()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.eclipseClasspath' to state Discove
red.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.eclipseJdt' rule action Project.<init>.t
asks.eclipseJdt()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.eclipseJdt using Project.<init>.tasks.eclipseJdt()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.eclipseJdt' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.eclipseProject' rule action Project.<ini
t>.tasks.eclipseProject()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.eclipseProject using Project.<init>.tasks.eclipseProje
ct()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.eclipseProject' to state Discovere
d.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.help' rule action tasks.addPlaceholderAc
tion(help)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.help using tasks.addPlaceholderAction(help)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.help' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.init' rule action tasks.addPlaceholderAc
tion(init)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.init using tasks.addPlaceholderAction(init)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.init' rule action Project.<init>.tasks.i
nit()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.init using Project.<init>.tasks.init()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.init' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.installApp' rule action Project.<init>.t
asks.installApp()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.installApp using Project.<init>.tasks.installApp()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.installApp' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.javadoc' rule action Project.<init>.task
s.javadoc()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.javadoc using Project.<init>.tasks.javadoc()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.javadoc' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.linux32' rule action Project.<init>.task
s.linux32()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.linux32 using Project.<init>.tasks.linux32()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.linux32' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.linux64' rule action Project.<init>.task
s.linux64()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.linux64 using Project.<init>.tasks.linux64()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.linux64' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.localclean' rule action Project.<init>.t
asks.localclean()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.localclean using Project.<init>.tasks.localclean()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.localclean' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.model' rule action tasks.addPlaceholderA
ction(model)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.model using tasks.addPlaceholderAction(model)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.model' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.os' rule action Project.<init>.tasks.os(
)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.os using Project.<init>.tasks.os()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.os' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.prepareGhPages' rule action Project.<ini
t>.tasks.prepareGhPages()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.prepareGhPages using Project.<init>.tasks.prepareGhPag
es()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.prepareGhPages' to state Discovere
d.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.projects' rule action tasks.addPlacehold
erAction(projects)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.projects using tasks.addPlaceholderAction(projects)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.projects' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.properties' rule action tasks.addPlaceho
lderAction(properties)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.properties using tasks.addPlaceholderAction(properties
)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.properties' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.publishGhPages' rule action Project.<ini
t>.tasks.publishGhPages()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.publishGhPages using Project.<init>.tasks.publishGhPag
es()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.publishGhPages' to state Discovere
d.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.run' rule action Project.<init>.tasks.ru
n()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.run using Project.<init>.tasks.run()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.run' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.runSliceBrowser' rule action Project.<in
it>.tasks.runSliceBrowser()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.runSliceBrowser using Project.<init>.tasks.runSliceBro
wser()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.runSliceBrowser' to state Discover
ed.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.setup' rule action Project.<init>.tasks.
setup()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.setup using Project.<init>.tasks.setup()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.setup' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.tasks' rule action tasks.addPlaceholderA
ction(tasks)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.tasks using tasks.addPlaceholderAction(tasks)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.tasks' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.test' rule action Project.<init>.tasks.t
est()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.test using Project.<init>.tasks.test()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.test' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.win32' rule action Project.<init>.tasks.
win32()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.win32 using Project.<init>.tasks.win32()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.win32' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.win64' rule action Project.<init>.tasks.
win64()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.win64 using Project.<init>.tasks.win64()
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.win64' to state Discovered.
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Running model element 'tasks.wrapper' rule action tasks.addPlaceholde
rAction(wrapper)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Mutating tasks.wrapper using tasks.addPlaceholderAction(wrapper)
11:09:15.781 [DEBUG] [org.gradle.model.internal.registry.DefaultModelRegistry] P
roject : - Transitioning model element 'tasks.wrapper' to state Discovered.
11:09:15.811 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :s
etupRemote (Thread[main,5,main]) started.
11:09:16.401 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :setupRemote
11:09:16.401 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceT
askExecuter] Starting to execute task ':setupRemote'
11:09:16.401 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskEx
ecuter] Determining if task ':setupRemote' is up-to-date
11:09:16.411 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExe
cuter] Executing task ':setupRemote' (up-to-date check took 0.01 secs) due to:
  Task has not declared any outputs.
11:09:16.411 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTask
Executer] Executing actions for task ':setupRemote'.
11:09:16.421 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceT
askExecuter] Finished executing task ':setupRemote'
11:09:16.421 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :setupRemote FAI
LED
11:09:16.421 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :s
etupRemote (Thread[main,5,main]) completed. Took 0.02 secs.
11:09:16.421 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] T
ask worker [Thread[main,5,main]] finished, busy: 0.02 secs, idle: 0.59 secs
11:09:16.421 [ERROR] [org.gradle.BuildExceptionReporter]
11:09:16.421 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed w
ith an exception.
11:09:16.421 [ERROR] [org.gradle.BuildExceptionReporter]
11:09:16.421 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
11:09:16.421 [ERROR] [org.gradle.BuildExceptionReporter] Build file 'C:\Users\Ro
bin\Desktop\photocentric_dev\host\build.gradle' line: 192
11:09:16.421 [ERROR] [org.gradle.BuildExceptionReporter]
11:09:16.421 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
11:09:16.421 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for ta
sk ':setupRemote'.
11:09:16.421 [ERROR] [org.gradle.BuildExceptionReporter] > No configured remotes
 match the the remote named: upstream
11:09:16.421 [ERROR] [org.gradle.BuildExceptionReporter]
11:09:16.421 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
11:09:16.421 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace o
ption to get the stack trace.
11:09:16.431 [LIFECYCLE] [org.gradle.BuildResultLogger]
11:09:16.431 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
11:09:16.431 [LIFECYCLE] [org.gradle.BuildResultLogger]
11:09:16.431 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 7.3 secs
11:09:16.431 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache task h
istory cache (C:\Users\Robin\Desktop\photocentric_dev\host\.gradle\2.14\taskArti
facts) was closed 0 times.
11:09:16.431 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache Genera
ted Gradle JARs cache (C:\Users\Robin\.gradle\caches\2.14\generated-gradle-jars)
 was closed 0 times.
11:09:16.431 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCach
e] Closing cache module-metadata.bin (C:\Users\Robin\.gradle\caches\modules-2\me
tadata-2.16\module-metadata.bin)
11:09:16.431 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCach
e] Closing cache artifact-at-repository.bin (C:\Users\Robin\.gradle\caches\modul
es-2\metadata-2.16\artifact-at-repository.bin)
11:09:16.431 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasin
g lock on artifact cache (C:\Users\Robin\.gradle\caches\modules-2).
11:09:16.431 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine
.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk
reads: 0 (avg: 0.0 secs, total: 0.0 secs)
11:09:16.431 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine
.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk
reads: 0 (avg: 0.0 secs, total: 0.0 secs)
11:09:16.431 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine
.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files
in 0.0 secs
11:09:16.431 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.me
mcache.InMemoryCachedRepositoryFactory] In-memory dependency metadata cache clos
ed. Repos cached: 3, cache instances: 3, modules served from cache: 0, artifacts
: 0
11:09:16.431 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCach
e] Closing cache plugin-use-metadata.bin (C:\Users\Robin\.gradle\caches\2.14\plu
gin-resolution\plugin-use-metadata.bin)
11:09:16.431 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasin
g lock on Plugin Resolution Cache (C:\Users\Robin\.gradle\caches\2.14\plugin-res
olution).
11:09:16.441 [DEBUG] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemo
nManager] Stopping 0 compiler daemon(s).
11:09:16.441 [INFO] [org.gradle.api.internal.tasks.compile.daemon.CompilerDaemon
Manager] Stopped 0 compiler daemon(s).

C:\Users\Robin\Desktop\photocentric_dev\host>

**Comment by WesGilster** [comment]
I'll try it out now.

**Comment by WesGilster** [comment]
Still works fine, I just built DEV016. Make sure you setup your gradle.properties if this is a new setup.

**Comment by jmkao** [comment]
The debug log doesn't really help, since that's more for debugging gradle than for debugging a build. What happens when you run it normally?

**Comment by kloknibor** [comment]
I used a new fork from WesGilster but all other forks fail too. I checked my gradle.properties and that only contains the release repo and the github key. Which are both fine and it exits on compilejava so it shouldn't have to do something with github yet I suppose. Als gradlew run fails.

**Comment by kloknibor** [comment]
@jmkao what do you mean with run it normally? The software runs when I download a release from github and with the normal gradlew command it runs and says build succefull.

**Comment by WesGilster** [comment]
He's saying that the debug statements are getting in the way of the actual problem which is:
No configured remotes match the the remote named: upstream

Which means your gradle.properties is probably bad:
`throw new GradleException("No configured remotes match the the remote named: ${releaseRepoRemoteName}");`

**Comment by kloknibor** [comment]
@WesGilster You are right, this was part of the problem but it still won't build here is the normal gradle run : 

```
D:\Github\Photonic3D_dev\host>gradlew run
:compileJava
D:\Github\Photonic3D_dev\host\src\main\java\org\area515\resinprinter\security\Je
ttySecurityUtils.java:40: error: cannot find symbol
import org.area515.resinprinter.util.security.LdapUtils;
                                             ^
  symbol:   class LdapUtils
  location: package org.area515.resinprinter.util.security
D:\Github\Photonic3D_dev\host\src\main\java\org\area515\resinprinter\security\ke
ystore\KeystoreUtilities.java:23: error: cannot find symbol
import org.area515.resinprinter.util.security.LdapUtils;
                                             ^
  symbol:   class LdapUtils
  location: package org.area515.resinprinter.util.security
2 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed with exit code 1; see the compiler error output for details
.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 9.417 secs

```

**Comment by kloknibor** [comment]
This can be closed. I tried a new clone from your repo @WesGilster and it seems to work now again :D Thanks for the help!

**Comment by WesGilster** [comment]
That second problem is a missing file due to a bad check-in to git-hub that I made.
