### ISSUE TITLE
It would be nice to see the currently printed image

### ISSUE THREAD

**Issue by WesGilster** [area515/Creation-Workshop-Host#27]

**Comment by kloknibor** [comment]
I also think this is a great feature, see my post at https://github.com/area515/Creation-Workshop-Host/issues/4 where I also used this feature :)

**Comment by WesGilster** [comment]
Implemented in cwh-0.89

**Comment by kloknibor** [comment]
Works like a charm!

**Comment by WesGilster** [comment]
Good, I'll close.
