### ISSUE TITLE
Need Raspberry Pi documentation

### ISSUE THREAD

**Issue by rockjim** [area515/Creation-Workshop-Host#32]
The code references an old version and then fails because files aren't available.

Lines 7,8,12 should be "cwh-0.80.zip" not "cwh-0.54.zip"

**Comment by kloknibor** [comment]
hi rockjim,

if you want to install it than take a look at this install guide : https://github.com/WesGilster/Creation-Workshop-Host/blob/master/host/installnotes.txt networkinstall isn't used anymore to install.

hope it helped,

Kloknibor

**Comment by rockjim** [comment]
Thanks. I was going off of the
https://github.com/area515/Creation-Workshop-Host/wiki/Raspberry-Pi-Manual-Setup-Instructions
that I was direct to from the wiki.

**Comment by kloknibor** [comment]
Sorry for the outdated wiki ;)! I'll try to update it this weekend :)

**Comment by WesGilster** [comment]
Documentation really needs cleaned up on the Wiki. So old. Maybe some screen shots to peak some interest, now that the camera, current slice and total cost are implemented.

**Comment by kloknibor** [comment]
Copied the description from the homepage to the wiki for now... will try to make a install clip when I have time

**Comment by WesGilster** [comment]
Since this bug was opened I think you've made two different install clips. Feel free to reopen if you don't want to track your progress under #208.
