### ISSUE TITLE
Download STL file from Internet URL/thingiverse directly

### ISSUE THREAD

**Issue by WesGilster** [area515/Creation-Workshop-Host#36]
Easy change, but I think it would be really cool to pull the image from a URL rather than forcing the user to download the image to their local harddrive and then uploading the image to CWH.

**Comment by WesGilster** [comment]
This works great now. Also fixed a classpath problem and binary stls should work as well. You'll be notified through a websocket message that the JobStatus is "Ready" to be printed.

Try it out by uploading this file:
http://www.thingiverse.com/download:888699

The functionality is available in cwh0.108

**Comment by kloknibor** [comment]
I get an http 500 error and that the printer is unresponsive... (I haven't connected a printer so far) how can I provide you with more debug information?

**Comment by WesGilster** [comment]
Again, I'll need the logs for this to know more.

**Comment by WesGilster** [comment]
Completed and tested in cwh-0.178 with new GUI.
