### ISSUE TITLE
New GUI needs to be optimized for Mobile

### ISSUE THREAD

**Issue by WesGilster** [area515/Creation-Workshop-Host#54]
The new GUI works with mobile, but it really needs to have some optimizations to make it cool

**Comment by WesGilster** [comment]
The specific bug I found was fixed in the latest version. I'm not sure this bug should be opened anymore. Need more testers

**Comment by kloknibor** [comment]
Sorry my printer is still down... When I recieve finally the right parts I will dtart testing again and when all draken printers are fixed or sended out you will have some testers :)!

**Comment by WesGilster** [comment]
No problem man I've still got to get these recent changes merged into 515.

**Comment by WesGilster** [comment]
Completed and tested in cwh-0.178 with new GUI.

Ergobot is working on a GUI that gracefully folds into mobile even better, but the current new gui works well enough.
