### ISSUE TITLE
Better error message when email fails

### ISSUE THREAD

**Issue by kloknibor** [area515/Creation-Workshop-Host#94]
Hi,

I'm having an error so I tried to send a .log bundle to myself but it's failing... I guess because I try to use an "@msn.com" account So I set the SMTP host to smtp.live.com but I guess there also needs to be a changed incoming port, is that correct? Or is it something else?

Robin

**Comment by WesGilster** [comment]
You'll need to look at the logs and send me the stack trace manually. 
Try these in this order:
1. Does MSN use port 587?
2. Does MSN use TLS?
3. If MSN uses TLS what is the port number?

If it's none of these, recheck your usernames and passwords. I use this 
function quite a bit. In the mean time, I'll rename this bug to give 
better feedback as to why the email failed.

Thanks,
Wes G.

**Comment by kloknibor** [comment]
According to this page : https://support.microsoft.com/en-us/kb/287604 

1 : Yes it does use port 587
2 : Yes MSN uses TLS
3 : Port 25 by default but port 587 is acceptable too if I understand it correct

will send you the files later

**Comment by WesGilster** [comment]
Much better error messages when email fails to send in cwh-0.185

**Comment by kloknibor** [comment]
Gonna try it tonight!

**Comment by kloknibor** [comment]
I get the following error : Failure emailing log bundle: 501 5.5.4 Invalid Email address

**Comment by kloknibor** [comment]
(trying on windows now quick)

**Comment by kloknibor** [comment]
Edit : I tried an gmail account and it blocked the mail because an app which doesn't apply to modern security tried to log in...  No option in the mail to give it acces anyway...

**Comment by kloknibor** [comment]
If more people experience this than log in to your google account , go here : https://www.google.com/settings/security/lesssecureapps and click enable ;)! Now Gmail works but msn still doens't for some reason...

**Comment by WesGilster** [comment]
I assume that it uses oath now. I'll open a feature request for that.
