### ISSUE TITLE
Print text files

### ISSUE THREAD

**Issue by WesGilster** [area515/Creation-Workshop-Host#98]
This is the next thing I want to print with abstract printing. Choose the font and size in print setup and upload like usual. Regular is fonts supported by default.

**Comment by WesGilster** [comment]
This is complete in the dev version cwh-0.215. You can pick the font name from any available system fonts and font size on the printer setup screen now.

I've also rearranged the printers screen, it still doesn't look great, but it uses two columns now.

**Comment by WesGilster** [comment]
It was my daughters birthday weekend so I didn't do anything except some print testing. These are my first tests for text file prints.

![image](https://cloud.githubusercontent.com/assets/2424628/13554641/e4df70ba-e372-11e5-98f6-010b181ff131.jpeg)

**Comment by kloknibor** [comment]
Looking nice Wes! And happy birthday to your daughter :)!

Verstuurd vanaf mijn iPhone
